version: '3'

services: 

  node-app:
    build: 
      context: node
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /usr/local/bin/docker-entrypoint.sh node index.js
    networks: 
      - node-network
    volumes: 
      - ./node/app:/usr/src/app
    tty: true
    depends_on: 
       - db

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx-node
    networks: 
      - node-network
    tty: true
    ports: 
      - "80:80"
    depends_on: 
       - node-app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      